#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /api/login
  controller: App\Controller\SecurityController:login

logout:
  path: /logout

authentication_token:
  path: /authentication_token
  methods: ['POST']